### ISSUE TITLE
Deployment broken over RequestsDependencyWarning

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/codeforlife-deploy-appengine#133]
When we try to run the `clusters_setup/deploy.py`, we come across the following error, stopping us from deploying:

```
/home/runner/.pyenv/2.7/local/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.24) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "clusters_setup/deploy.py", line 2, in <module>
    import kubernetes
  File "/home/runner/.pyenv/2.7/local/lib/python2.7/site-packages/kubernetes/__init__.py", line 20, in <module>
    import kubernetes.config
  File "/home/runner/.pyenv/2.7/local/lib/python2.7/site-packages/kubernetes/config/__init__.py", line 17, in <module>
    from .kube_config import (list_kube_config_contexts, load_kube_config,
  File "/home/runner/.pyenv/2.7/local/lib/python2.7/site-packages/kubernetes/config/kube_config.py", line 22, in <module>
    import google.auth.transport.requests
  File "/home/runner/.pyenv/2.7/local/lib/python2.7/site-packages/google/auth/transport/requests.py", line 31, in <module>
    caught_exc,
  File "/home/runner/.pyenv/2.7/local/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
ImportError: The requests library is not installed, please install the requests package to use the requests transport.
```

To reproduce: 

- Try to deploy on staging

**Comment by shuxinpei** [comment]
Then how you solved this problem? thank you.
